services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: simon
      MYSQL_PASSWORD: simon
    ports:
      - 3307:3306
    volumes:
     - "./database:/docker-entrypoint-initdb.d"