app:
  name: "RestaurantApp"
  db:
    name: restaurant
    host: localhost
    port: 3307
    username: "simon"
    password: "simon"
spring:
  application:
    name: "visie.excersise.spring.restaurant"
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "${app.db.user}"
    password: "${app.db.password}"
    url: "jdbc:mysql://${app.db.host}:${app.db.port}/${app.db.name}"
  flyway:
    enabled: true
    user: "${app.db.username}"
    password: "${app.db.password}"
    url: "${spring.datasource.url}"
flyway:
  locations: "classpath:db/migration"